### ISSUE TITLE
Publish the extension

### ISSUE THREAD

**Issue by kiurchv** [raulchedrese/nova-elixir-ls#1]
Thank you for your work on bringing Elixir support to Nova!
Since this is most feature-rich Nova extension for Elixir I believe that it should be submitted to Nova's extension library and available to use by other developers

**Comment by raulchedrese** [comment]
Hey @kiurchv, I've published the extension to Nova's extension library. Please give it a try and let me know if you run into problems.

**Comment by kiurchv** [comment]
Thanks!
