### ISSUE TITLE
Syntax highlighting problem with function definition without 'end'

### ISSUE THREAD

**Issue by zacksiri** [raulchedrese/nova-elixir-ls#10]
As you can see here the syntax highlighting is still off for cases like this. Anything we can do?

<img width="933" alt="Screen Shot 2021-08-02 at 12 09 24 PM" src="https://user-images.githubusercontent.com/134488/127807097-db6d6340-e074-44a7-8072-44deae3035e8.png">

**Comment by raulchedrese** [comment]
Hey @zacksiri, thanks for taking the time to submit an issue! I think I was able to resolve this in the latest release. Can you update your extension and take a look?

**Comment by zacksiri** [comment]
@raulchedrese yes indeed it works!, this made my day!
