### ISSUE TITLE
Causing crash in Nova 7.4

### ISSUE THREAD

**Issue by zacksiri** [raulchedrese/nova-elixir-ls#12]
I'm having problems with this extension. When It's installed and active, and I try to do any change to an elixir file it crashes the Editor.

**Comment by raulchedrese** [comment]
Hey @zacksiri, thanks for creating an issue! I can't seem to reproduce your issue. Can you update to the latest version of the extension and let me know which version of Elixir you are running? Also is it crashing when editing a `.exs` file or `.ex` file?

**Comment by zacksiri** [comment]
@raulchedrese it cashes whether it's `.exs` or `.ex` doesn't matter. It's very strange. This didn't happen on Nova 7.2 (the verison I was happily using before)

I'm already using extension version 0.3.5

I am running elixir 1.9.4

**Comment by raulchedrese** [comment]
@zacksiri the Elixir Language Server, that this extension relies, no longer supports Elixir 1.9. You'll need to update to at least 1.10. Hope that helps!

**Comment by zacksiri** [comment]
Hey @raulchedrese I got confirmation from Nova developers that there is a bug in 7.4 causing the crash. I will close this issue.

Thank you for taking the time to respond! Much appreciated!
