### ISSUE TITLE
syntax highlighting ignores end keywords

### ISSUE THREAD

**Issue by colinstark** [raulchedrese/nova-elixir-ls#14]
The syntax highlighting ignores end & do keywords:

<img width="184" alt="syntax-ls" src="https://user-images.githubusercontent.com/5658185/138494962-9ca892fb-871a-4dea-86b7-9c7ed92ceb20.png">
In comparison, Rusty Patched's extension looks more like how the ruby syntax highlighting works.

<img width="154" alt="syntax-rusty" src="https://user-images.githubusercontent.com/5658185/138494970-433da7b2-251d-402b-a977-bc6c3f333997.png">

**Comment by raulchedrese** [comment]
Hey Colin, thanks for taking the time to submit an issue!

This should be resolved on the latest version of the extension.
