### ISSUE TITLE
Format on save does not work

### ISSUE THREAD

**Issue by tobiastom** [raulchedrese/nova-elixir-ls#17]
I have enabled the format on save option, but when I save a document, it does not get formatted.
Running `mix format <filename>` from the terminal works fine. 

I can find the following error message in the extension console, but it does not help me much to debug it further:

```
Cannot format file from current directory (Currently in .)
```

**Comment by hfjallemark** [comment]
Same here, although I'm not seeing that error message in the extension console.

**Comment by raulchedrese** [comment]
Formatting has been finicky. I previously fixed an issue with file paths that was causing formatting to stop working but looks like there may be another bug. If anyone is interested in attempting a fix please do! The format command is being dispatched [here](https://github.com/raulchedrese/nova-elixir-ls/blob/master/src/commands/formatting.ts#L18). 

@tobiastom  in your case it looks like the format command is being sent but failing. This will likely require debugging on the [ElixirLS](https://github.com/elixir-lsp/elixir-ls) end to see what would cause that error. Searching the ElixirLS code base for that error message might be a good place to start. 

@hfjallemark in your case it looks like the command may be failing to send. You could throw some `console.log` calls [here](https://github.com/raulchedrese/nova-elixir-ls/blob/master/src/commands/formatting.ts#L17) to verify if it is getting called.

**Comment by tobiastom** [comment]
My issue seems to be fixed with Nova 9 and format on save works for me.

**Comment by BryanJBryce** [comment]
Does not work for me Nova 9.2

**Comment by tobiastom** [comment]
~~Unfortunately I can confirm this.~~

For me it was just disabled inside the settings. Enabling the "Format on save" option, disabling and enabling the extension made format on save work again.

**Comment by raulchedrese** [comment]
I'm going to close this because "Format on save" appears to be more reliable in newer versions of Nova. If you are still experiencing this please post here with the output of your extension console.
