### ISSUE TITLE
Elixir Icons not working

### ISSUE THREAD

**Issue by Dieman89** [raulchedrese/nova-elixir-ls#19]
<img width="167" alt="image" src="https://user-images.githubusercontent.com/28837891/158666895-390de0c7-933c-44b1-8aaa-7d9732b76019.png">

I am not sure if it's because of Nova 9?

**Comment by raulchedrese** [comment]
Hey @Dieman89, thanks for opening an issue!

Did Nova ever show icons for Elixir files? I don't recall. If it did then I think this is an issue we should report to Nova. The icons are not provided by the extension.

**Comment by rhysforyou** [comment]
Previous versions of Nova used whatever icon was registered for a file type at the system level. With Nova 9, they've switched to using custom icons, and have evidently not provided icons for Elixir file types. There's nothing extensions can do about this right now, so it's probably outside the scope of this project.

**Comment by raulchedrese** [comment]
@rhysforyou, @Dieman89  I've posted a feature request on the Nova Dev Forum here: https://devforum.nova.app/t/file-icon-for-elixir-files/1686. Not sure there is much more we can do other than hit the like button on that post.

**Comment by raulchedrese** [comment]
Closing because this is a limitation of Nova and can't currently be resolved by this extension.

**Comment by raulchedrese** [comment]
Nova 10 has added icons for Elixir files!
