### ISSUE TITLE
Add syntax highlighting to support HEEx syntax inside of ~H

### ISSUE THREAD

**Issue by BryanJBryce** [raulchedrese/nova-elixir-ls#20]
Currently syntax highlighting doesn't work for HEEx code inside of ~H

**Comment by BryanJBryce** [comment]
This has already been done for VSCode, with a little direction on how to convert it to Nova I'd take this on:
https://github.com/phoenixframework/vscode-phoenix

**Comment by raulchedrese** [comment]
Hey @BryanJBryce, thanks for opening an issue! 

I've added very basic support for HEEx templates. Now when Nova encounters `~H"""` in a Elixir file it will apply the syntax highlighting rules defined in https://github.com/raulchedrese/nova-elixir-ls/blob/master/ElixirLS.novaextension/Syntaxes/eex.xml.

Those rules don't currently work that well so if you'd like to improve them that would be awesome. If I was going to tackle this I'd likely do the following:
- Create a sample syntax file that includes all the HEEx syntax. This will be useful for testing and avoiding regressions.
- Read up on how to define Scopes in Nova https://docs.nova.app/syntax-reference/scopes/
- Add rules to the [syntax definition](https://github.com/raulchedrese/nova-elixir-ls/blob/master/ElixirLS.novaextension/Syntaxes/eex.xml.) until your sample syntax file is highlighted the way you expect.

**Comment by raulchedrese** [comment]
@BryanJBryce this should now be resolved with the newest version of the extension in Nova 10. I've added syntax highlighting for HEEx using the new syntax highlighting engine in Nova 10.
