### ISSUE TITLE
Not all symbols are available

### ISSUE THREAD

**Issue by eahanson** [raulchedrese/nova-elixir-ls#22]
When I use "Open Quickly in Symbols…", I get an incomplete list of symbols. I can't see a pattern to which symbols are found vs. not found. I've tried removing my .elixir_ls directory but it doesn't help. My project isn't particularly big: 78 Elixir files and 86 Elixir test files.

I'm happy to dig in and try to figure out what's going on, but I could use a point in the right direction.

Do you have an open source Elixir project that you use to test that this plugin is working? I tried opening the Phoenix LiveView project in Nova, but after compiling and waiting until the ElixirLS messages stopped appearing in Nova's extension console, it wouldn’t list *any* modules. 

Do you have any other troubleshooting/debugging hints? Thx!

**Comment by raulchedrese** [comment]
Hey @eahanson, thanks for taking the time to open an issue!

This sounds like an issue with how we are defining "symbols" in the the new TreeSittter query language. The queries are [here](https://github.com/raulchedrese/nova-elixir-ls/blob/master/ElixirLS.novaextension/Queries/symbols.scm). The relevant  Nova documentation is [here](https://docs.nova.app/syntax-reference/tree-sitter/#symbolication)

The fix may be as simple as renaming the variables/captures, the parts of the query that start with `@`, to match the ones defined in the linked Nova documentation. Might be a few weeks before I can dive into this so if you are interested in taking a crack at it please do!

I don't have an open source project I use to test, although it would be nice to have one. I'll take a look at the LiveView project and see why it isn't working.

**Comment by eahanson** [comment]
I have not had as much time as I had hoped to look into this. I still hope to find the time, though if anyone else is interested in having a look, don't let me stop you 🙂.

**Comment by eahanson** [comment]
I updated the plugin on my computer to the new version and deleted my `.elixir_ls` directory, and then "Open Quickly in Symbols" started working. 🎉
