### ISSUE TITLE
Support for ElixirLS v0.15.1?

### ISSUE THREAD

**Issue by eahanson** [raulchedrese/nova-elixir-ls#30]
ElixirLS 0.15.1 now supports OTP 26. 

@raulchedrese what do you think about updating nova-elixir-ls to use Elixir LS 0.15.1? Or would you prefer if I created a PR to update the version?

**Comment by raulchedrese** [comment]
Hey @eahanson, I should be able to publish an updated version later today. I've been running a version with ElixirLS 0.15.1 locally for a couple days and haven't run into any new issues.

**Comment by raulchedrese** [comment]
I've shipped 0.4.5 with ElixirLS 0.15.1. Let me know if you run into issues!
