### ISSUE TITLE
Compile errors and dialyzer warnings not showing

### ISSUE THREAD

**Issue by mratliff** [raulchedrese/nova-elixir-ls#7]
Most of the functionality (completion, syntax highlighting, etc) working. But cannot see any compile error reporting or dialyzer warnings. 

Is there additional configuration that is needed to enable this?

**Comment by raulchedrese** [comment]
Hey @mratliff, thank you for taking the time to open an issue. Can you take a look for any errors in your extension console? If you don't see the "Extensions" menu item you will need to enable it in Nova settings.

**Comment by mratliff** [comment]
No errors are generated in console.
It WILL show errors upon launch of Nova (if they existed from previous edit session).
Any new errors are not noticed by the extension. 
Upon start up I do get an error dialog from Elixir Language Server that says "Did not receive workspace/ didChangeConfiguration notification after 5 seconds
![Screen Shot 2021-03-19 at 1 50 21 PM](https://user-images.githubusercontent.com/5023/111835336-739e9780-88ba-11eb-9021-84e3454a436e.png)

Here is the console dump of what happens on start up with a file that contains an error present (you will see the extension picks up that error of the missing Enum.any/0 functions).

ElixirLS[13:49:08.265000] activating Elixir LS...

ElixirLS[13:49:08.266000] lange-server-path updated

ElixirLS[13:49:08.266000] Start Server

Elixir Language Server[13:49:09.444000] Started ElixirLS v0.6.4

Elixir Language Server[13:49:09.446000] Elixir version: "1.11.3 (compiled with Erlang/OTP 23)"

Elixir Language Server[13:49:09.446000] Erlang version: "23"

Elixir Language Server[13:49:09.446000] ElixirLS compiled with Elixir 1.10.4 and erlang 23

Elixir Language Server[13:49:16.814000] MIX_ENV: test

Elixir Language Server[13:49:16.814000] MIX_TARGET: host

Elixir Language Server[13:49:17.611000] Compiling 2 files (.ex)

Elixir Language Server[13:49:17.824000] warning: Enum.any?/0 is undefined or private. Did you mean one of:

      * any?/1
      * any?/2

  lib/dynamic_optimization/geo.ex:21: DynamicOptimization.Geo.randomNearbyLatLng/4


Elixir Language Server[13:49:18.254000] Compile took 1390 milliseconds

Elixir Language Server[13:49:18.254000] [ElixirLS Dialyzer] Checking for stale beam files

Elixir Language Server[13:49:18.254000] [ElixirLS WorkspaceSymbols] Indexing...

Elixir Language Server[13:49:18.688000] [ElixirLS WorkspaceSymbols] Module discovery complete

Elixir Language Server[13:49:18.801000] [ElixirLS Dialyzer] Found 2 changed files in 131 milliseconds

Elixir Language Server[13:49:18.919000] [ElixirLS WorkspaceSymbols] 23 callbacks added to index

Elixir Language Server[13:49:19.093000] [ElixirLS WorkspaceSymbols] 259 modules added to index

Elixir Language Server[13:49:19.125000] [ElixirLS Dialyzer] Analyzing 1 modules: [DynamicOptimization.Geo]

Elixir Language Server[13:49:19.493000] [ElixirLS WorkspaceSymbols] 315 types added to index

Elixir Language Server[13:49:20.056000] [ElixirLS Dialyzer] Analysis finished in 1244 milliseconds

Elixir Language Server[13:49:20.170000] Dialyzer analysis is up to date

Elixir Language Server[13:49:21.456000] [ElixirLS Dialyzer] Writing manifest...

Elixir Language Server[13:49:22.601000] [ElixirLS Dialyzer] Done writing manifest in 2422 milliseconds.

Elixir Language Server[13:49:24.836000] [ElixirLS WorkspaceSymbols] 4999 functions added to index

**Comment by chipotle** [comment]
I'm finding this same issue: errors in Elixir code are found on first load if the file is already open when the language server starts, but the code clearly isn't being checked afterward. You can demonstrate this by introducing an obvious syntax error into an Elixir file -- I changed a function name to have a typo in it -- and the syntax error won't be caught, even after the file is saved. Exit Nova and relaunch it, and the error will be caught then.

**Comment by mratliff** [comment]
any word on this? This one blocker basically makes the extension useless in my context....

**Comment by raulchedrese** [comment]
Hey @mratliff, I'm still looking into this issue. As far as I can tell it appears to be an issue with Nova's implementation of the Language Server Protocol. I've opened a topic on their developer forum to get some clarification.

**Comment by raulchedrese** [comment]
Alright folks I believe this is a bug with Nova but they have yet to respond to my bug report. In the meantime I think I have figured out a workaround by manually triggering a recompile when a file is saved instead of relying on Nova to do it. I've submitted an updated version of the extension. Give it a try when you get a chance and let me know how it goes!

**Comment by mratliff** [comment]
I don't think this is the case. There is another elixir-ls server in the library. And this functionality works in that one. Unfortunately the GitHub repo is not online so there is no way for me to look at the code and determine the difference. But I appreciate the workaround and I will give it a go!

**Comment by mratliff** [comment]
Looks like the workaround is doing its thing! Thank you. I hope that the core issue is found and worked through. Tough times with new tools...
