### ISSUE TITLE
Go to Definition broken on OTP 24 Elixir 1.12

### ISSUE THREAD

**Issue by mratliff** [raulchedrese/nova-elixir-ls#9]
Just what it says

**Comment by raulchedrese** [comment]
Hey @mratliff, can you take a peak at the Extension Console and see if any errors are popping up there?

**Comment by mratliff** [comment]
Seems like it is still living in an OTP 23 land....what needs to be done to update?

Output on start up:

Elixir Language Server[6:48:34.347000] Started ElixirLS v0.6.5

Elixir Language Server[6:48:34.351000] Elixir version: "1.11.4 (compiled with Erlang/OTP 23)"

Elixir Language Server[6:48:34.351000] Erlang version: "23"

Elixir Language Server[6:48:34.351000] ElixirLS compiled with Elixir 1.11.3 and erlang 23

Elixir Language Server[6:48:39.541000] Skipping build because cwd changed from /Volumes/Macintosh HD/Users/mikeratliff/code/clients/cpower/dynamic_optimization to /Users/mikeratliff/code/clients/cpower/dynamic_optimization

Elixir Language Server[6:48:40.589000] Dialyzer analysis is up to date

**Comment by raulchedrese** [comment]
Hey @mratliff, the extension should be using your installed version of Elixir. Does your terminal show a different version if you run `elixir --version`?

I think the reason "Go to Definition" isn't working is due to this error "Skipping build because cwd changed...". I opened an [issue](https://github.com/elixir-lsp/elixir-ls/issues/575) on the elixir-ls project to get this resolved.

**Comment by jamiedumont** [comment]
I can +1 this issue, and it appears to be more widespread than just the "Go to definition" function.

I'm getting the following just opening a `.ex` file:

```
ElixirLS[21:14:50.493000] Project Dir:

ElixirLS[21:14:50.493000] /Volumes/Macintosh HD/Users/jamie/Sites/pento

Elixir Language Server[21:14:50.761000] Started ElixirLS v0.7.0

Elixir Language Server[21:14:50.763000] Elixir version: "1.12.1 (compiled with Erlang/OTP 24)"

Elixir Language Server[21:14:50.763000] Erlang version: "24"

Elixir Language Server[21:14:50.763000] ElixirLS compiled with Elixir 1.9.4 and erlang 22

Prettier[21:14:51.929000] Loading bundled prettier at /Users/jamie/Library/Application Support/Nova/Extensions/alexanderweiss.prettier/node_modules/prettier

Prettier[21:14:51.930000] Loading prettier at /Users/jamie/Library/Application Support/Nova/Extensions/alexanderweiss.prettier/node_modules/prettier

Prettier[21:14:51.931000] Starting Prettier service

Elixir Language Server[21:14:56.574000] Skipping build because cwd changed from /Volumes/Macintosh HD/Users/jamie/Sites/pento to /Users/jamie/Sites/pento

```

I'm getting mismatched Elixir and Erlang versions between my installed and the LS. I used asdf for the install if that makes a difference? But running `elixir --version` in any terminal shows 1.12.1 so it's available globally.

**Comment by raulchedrese** [comment]
@mratliff @jamiedumont I've released an updated version of the extension that I think will resolve the issues you are seeing. If you get a chance please try it out and let me know!

**Comment by mratliff** [comment]
Yes it works! Thank you so much.
